name: Python Workflows
on: [push]
jobs:
    Unit-Testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.7.12
              uses: actions/setup-python@v2
              with:
                python-version: "3.7.12"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt]; then pip install -r requirements.txt; fi
            - name: Run Tests
              run: |
                python -m unittest tests/test_app.py
